name: Tim Balzer
favicon: null
layout_spectrum: 0.49463468650355935
typography_spectrum: 0.5401734735351056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.502293718745932
  lightness: 0.4741838783957064
  saturation: 0.8700995619874448
  rhythmicContrast: 0.22593637206591666
purpose: []
