name: Tim Balzer
favicon: null
layout_spectrum: 0.34222611342556775
typography_spectrum: 0.6100353717338294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1942285760305822
  lightness: 0.04009624547325075
  saturation: 0.5244212846737355
  rhythmicContrast: 0.6293381804134697
purpose: []
