name: Tim Balzer
favicon: null
layout_spectrum: 0.4765149138402194
typography_spectrum: 0.25865978049114347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.47599787125363946
  lightness: 0.7033775937743485
  saturation: 0.7970253846142441
  rhythmicContrast: 0.002398889744654298
purpose: []
