name: Tim Balzer
favicon: null
layout_spectrum: 0.5692630235571414
typography_spectrum: 0.11725311959162354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6412093618419021
  lightness: 0.7686197576113045
  saturation: 0.09387295600026846
  rhythmicContrast: 0.538665677420795
purpose: []
