name: Tim Balzer
favicon: null
layout_spectrum: 0.3985194768756628
typography_spectrum: 0.23977242154069245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2703123700339347
  lightness: 0.4314014797564596
  saturation: 0.9833361837081611
  rhythmicContrast: 0.36580923292785883
purpose: []
